name: budget
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  path_provider: ^2.0.9
  xml: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  isar_generator: ^2.2.1
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
